### ISSUE TITLE
Failed to import - fetch-blob

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#163]
## Failing module

- **GitHub**:  https://github.com/node-fetch/fetch-blob
- **npm**: https://www.npmjs.com/package/fetch-blob

```js
import { Blob } from 'https://esm.sh/fetch-blob'
```

## Error message

After running `deno run` I get this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "Could not resolve \"stream/web\"");
export default null;
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14

The line causing this issue: https://github.com/node-fetch/fetch-blob/blob/0e074572462f2df71c2507f187f164c61376257e/streams.cjs#L7

The module that needs to be added to polyfills: https://nodejs.org/api/webstreams.html#webstreams_web_streams_api

**Comment by Stradivario** [comment]
I can see now it is working

```
curl https://esm.sh/fetch-blob
```

shows

```
/* esm.sh - fetch-blob@3.1.2 */
export * from "https://cdn.esm.sh/v53/fetch-blob@3.1.2/es2021/fetch-blob.js";
export { default } from "https://cdn.esm.sh/v53/fetch-blob@3.1.2/es2021/fetch-blob.js";
```

Cheers

**Comment by talentlessguy** [comment]
new error now on v55:

```sh
➜ deno eval 'import { Blob } from \'https://esm.sh/fetch-blob\''
Check a generated module
error: Uncaught SyntaxError: Identifier '__process$' has already been declared
    at <anonymous> (https://cdn.esm.sh/v55/fetch-blob@3.1.3/deno/fetch-blob.js:2:328)
```

**Comment by talentlessguy** [comment]
blocked by this on v57: https://github.com/denoland/deno_std/pull/1519 (not esm.sh bug)

**Comment by talentlessguy** [comment]
main module is now importing fine on v58 but `fetch-blob/from.js` breaks because of `worker_threads`:

```
➜ deno eval "import {File, Blob, blobFrom, blobFromSync, fileFrom, fileFromSync} from 'https://esm.sh/fetch-blob/from.js'"
Download https://esm.sh/fetch-blob/from.js
Download https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=fetch-blob
Check a generated module
error: Import 'https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=worker_threads&importer=fetch-blob' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v58/fetch-blob@3.1.3/deno/from.js:2:1982
```

**Comment by talentlessguy** [comment]
New error on v111:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "can not build 'file.js': can not build 'index.js': can not build 'streams.cjs': resovleESModule: open /tmp/esm-build-317b0017fa0b2b447e572409cd2667e1d5e63653-573b649a/node_modules/fetch-blob/streams.cjs.js: no such file or directory");
export default null;
```

**Comment by talentlessguy** [comment]
works on v135
