### ISSUE TITLE
Failed to import - prompts

### ISSUE THREAD

**Issue by rotu** [esm-dev/esm.sh#170]
## Failing module

- **GitHub**: https://github.com/terkelg/prompts
- **npm**: https://www.npmjs.com/package/prompts

```js
import * as prompts from "https://esm.sh/prompts"
```

## Error message

After importing I get this:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at cl (https://cdn.esm.sh/v53/prompts@2.4.1/deno/prompts.js:98:3283)
    at https://cdn.esm.sh/v53/prompts@2.4.1/deno/prompts.js:98:3391
    at https://cdn.esm.sh/v53/prompts@2.4.1/deno/prompts.js:2:679
    at https://cdn.esm.sh/v53/prompts@2.4.1/deno/prompts.js:98:3425
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14.1

**Comment by talentlessguy** [comment]
this seems to be the cause of this error:

```
src = __Process$.versions.node.split(".").map(Number);
```

esm.sh should use deno process for this, not `process` polyfill

**Comment by talentlessguy** [comment]
Seems to be working on v71:

```ts
> import * as prompts from "https://esm.sh/prompts"
Module {
  default: <ref *1> [AsyncFunction: R] AsyncFunction {
    prompt: [Circular *1],
    prompts: {
      text: [Function],
      password: [Function],
      invisible: [Function],
      number: [Function],
      date: [Function],
      confirm: [Function],
      list: [Function],
      toggle: [Function],
      select: [Function],
      multiselect: [Function],
      autocompleteMultiselect: [Function],
      autocomplete: [Function]
    },
    inject: [Function: al],
    override: [Function: cl]
  }
}

```

**Comment by rotu** [comment]
confirmed it works now
