### ISSUE TITLE
Failed to import - micromark

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#179]
## Failing module

- **GitHub**: https://github.com/micromark/micromark
- **npm**: https://www.npmjs.com/package/micromark

```js
import { micromark } from 'https://esm.sh/micromark'
```

## Error message

After running `deno run` I get this:

```
error: Uncaught SyntaxError: The requested module '/v53/micromark@3.0.5/deno/lib/compile.js' does not provide an export named 'compile'
    at <anonymous> (https://cdn.esm.sh/v53/micromark@3.0.5/deno/lib/preprocess.js:2:8)
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14.1

Related: #135

**Comment by talentlessguy** [comment]
still having this error on v55:

```
Download https://cdn.esm.sh/v55/micromark-util-classify-character@1.0.0/deno/micromark-util-classify-character.js
error: Uncaught SyntaxError: The requested module '/v55/micromark@3.0.7/deno/lib/compile.js' does not provide an export named 'compile'
    at <anonymous> (https://cdn.esm.sh/v55/micromark@3.0.7/deno/lib/preprocess.js:2:8)
```

**Comment by talentlessguy** [comment]
now there is this error:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "open /tmp/esm-build-51f68c63852483f342490b39fc2b713cc1da1a2d-22c5ca0c/node_modules/micromark/package.json: no such file or directory");
export default null;
```

**Comment by ije** [comment]
<img width="571" alt="Screenshot 2022-01-04 at 23 58 44" src="https://user-images.githubusercontent.com/2883484/148087004-bc01109e-f1ea-442e-899c-beb315ee7ee5.png">
seems it works in my local server

**Comment by talentlessguy** [comment]
@ije could you clean up the build dir for CDN then please

**Comment by aiotter** [comment]
Still having a problem in importing `micromark@3.0.10`. 

```ts
> import { micromark } from 'https://esm.sh/micromark@3.0.10'
Uncaught SyntaxError: The requested module '/v64/micromark@3.0.10/deno/lib/postprocess.js' does not provide an export named 'postprocess'
    at async <anonymous>:2:29
```

```ts
// https://esm.sh/micromark@3.0.10/deno/lib/postprocess.js

/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Package path ./deno/lib/postprocess is not exported from package /tmp/esm-build-1af3155c4d51507d2cc6db59e44781bab679561a-505e9804/node_modules/micromark (see exports field in /tmp/esm-build-1af3155c4d51507d2cc6db59e44781bab679561a-505e9804/node_modules/micromark/package.json)");
export default null;
```

You can see a function `postprocess` is exported here.
https://github.com/micromark/micromark/blob/3.0.10/packages/micromark/dev/lib/postprocess.js

**Comment by wooorm** [comment]
Similar on v65:

```sh
$ deno eval 'import { micromark } from "https://esm.sh/micromark"'
```

Yields:

```
Download https://esm.sh/micromark
Download https://cdn.esm.sh/v65/micromark@3.0.10/deno/micromark.js
Download https://cdn.esm.sh/v65/micromark@3.0.10/dev/index.d.ts
Download https://cdn.esm.sh/v65/micromark-util-types@1.0.2/index.d.ts
error: Uncaught SyntaxError: The requested module '/v65/micromark@3.0.10/deno/lib/parse.js' does not provide an export named 'parse'
    at <anonymous> (https://cdn.esm.sh/v65/micromark@3.0.10/deno/lib/preprocess.js:2:76)
```

For some reason [`/deno/lib/parse.js` on the CDN](https://cdn.esm.sh/v65/micromark@3.0.10/deno/lib/parse.js) does not match what’s in [the source](https://github.com/micromark/micromark/blob/main/packages/micromark/dev/lib/parse.js). Instead, it matches [the project’s main file](https://github.com/micromark/micromark/blob/main/packages/micromark/dev/index.js)

**Comment by wooorm** [comment]
Awesome!

**Comment by ije** [comment]
@wooorm btw [micromark](https://github.com/micromark/) is amazing!

**Comment by aiotter** [comment]
Nice work!

**Comment by aiotter** [comment]
Thanks for v66, I finally succeed in importing MDX in deno!
Thank you again to @ije, and of to @wooorm for great micromark package! I'll use micromark instead of markdown-it ;-)

```ts
import "https://esm.sh/@mdx-js/mdx@v2.0.0?pin=v66&alias=astring:https://deno.land/x/astring@v1.8.1/src/astring.js";
Module {
  compile: [Function: T],
  compileSync: [Function: _],
  createProcessor: [Function: j],
  evaluate: [AsyncFunction: $e],
  evaluateSync: [Function: Ke],
  nodeTypes: [
    "mdxFlowExpression",
    "mdxJsxFlowElement",
    "mdxJsxTextElement",
    "mdxTextExpression",
    "mdxjsEsm"
  ],
  run: [AsyncFunction: L],
  runSync: [Function: N]
}
```
