### ISSUE TITLE
Failed to import - styled-jsx

### ISSUE THREAD

**Issue by call-a3** [esm-dev/esm.sh#192]
## Failing module

- **GitHub**: https://github.com/vercel/styled-jsx/blob/master/src/style.js
- **npm**: https://www.npmjs.com/package/styled-jsx

```js
import _JSXStyle from "https://esm.sh/styled-jsx@4.0.1/style";
```

## Error message

After running `deno run` I get this:

```
Download https://cdn.esm.sh/v54/@types/styled-jsx@3.4.4/style...d.ts
Check file:///home/adriaan/dn/dashboard/index.ts
error: Error: Unable to resolve media type for specifier: "https://cdn.esm.sh/v54/@types/styled-jsx@3.4.4/style...d.ts"
    at deno:core/01_core.js:101:46
    at unwrapOpResult (deno:core/01_core.js:121:13)
    at Object.opSync (deno:core/01_core.js:135:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:340:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:111714:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:111980:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:112077:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:113535:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:113336:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:113197:26)
```

## Additional info

- **esm.sh version**: v54
- **Deno version**: 1.14.3

**Comment by talentlessguy** [comment]
new error with v55:

```js
Uncaught ReferenceError: document is not defined
    at new s (https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:2:1830)
    at new s (https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:10:1837)
    at https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:11:1100
    at https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:2:574
    at https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:11:1468
    at https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:2:574
    at https://cdn.esm.sh/v55/styled-jsx@4.0.1/deno/style.js:11:1482
```

**Comment by ije** [comment]
@talentlessguy `document` only works in browsers
