### ISSUE TITLE
Failed to import - `box-node-sdk`

### ISSUE THREAD

**Issue by roseMix** [esm-dev/esm.sh#196]
## Failing module

- **GitHub**:  https://github.com/box/box-node-sdk
- **npm**: https://www.npmjs.com/package/box-node-sdk

```js
 import BoxSDK from 'https://esm.sh/box-node-sdk'
```

## Error message

After running `deno run` I get this:

```
Uncaught TypeError: Import 'https://cdn.esm.sh/error.js?type=unsupported-nodejs-builtin-module&name=dns&importer=socks-proxy-agent' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v54/socks-proxy-agent@5.0.1/deno/socks-proxy-agent.js:2:264
    at async <anonymous>:2:30
```

## Additional info

- **esm.sh version**: v47
- **Deno version**: 1.13.0

**Comment by talentlessguy** [comment]
having this on v55 now:

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.setPrototypeOf (<anonymous>:null:null)
    at https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:2:2879
    at ve (https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:2:2901)
    at B (https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:3:655)
    at https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:3:540
    at https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:2:823
    at https://cdn.esm.sh/v55/graceful-fs@4.2.8/deno/graceful-fs.js:3:4405
```

**Comment by talentlessguy** [comment]
still on v57

this seems to be causing the error:

```js
 if (Object.setPrototypeOf)
          Object.setPrototypeOf(read, fs$read);
        return read;
```
