### ISSUE TITLE
Failed to import - @polkadot/api

### ISSUE THREAD

**Issue by danforbes** [esm-dev/esm.sh#232]
## Failing module

- **GitHub**: https://github.com/polkadot-js/api/tree/master/packages/api
- **npm**: https://www.npmjs.com/package/@polkadot/api

```js
import { ApiPromise, WsProvider } from "https://esm.sh/@polkadot/api";
```

## Error message

After running `deno run` I get this:

```
dot-deno: deno run index.ts 
Download https://cdn.esm.sh/v58/@babel/runtime@7.16.5/deno/helpers/esm/classPrivateFieldLooseBase.js
Download https://cdn.esm.sh/v58/@babel/runtime@7.16.5/deno/helpers/esm/classPrivateFieldLooseKey.js
error: Import 'https://cdn.esm.sh/v58/@babel/runtime@7.16.5/deno/helpers/esm/classPrivateFieldLooseKey.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v58/@polkadot/x-textencoder@8.1.2/deno/x-textencoder.js:2:103
```

## Additional info

```
dot-deno: deno --version
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

**Comment by talentlessguy** [comment]
this is the error

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "parseCJSModuleExports: Can't resolve '@babel/runtime/helpers/esm/classPrivateFieldLooseKey' in '/tmp/esm-build-61744e53cab3e9e890d2936809017cca7b61a3c6-ac4b4521'");
export default null;
```

module resolution errors

**Comment by talentlessguy** [comment]
another error on v60:

```
Uncaught SyntaxError: The requested module '/v60/@polkadot/x-global@8.2.2/deno/x-global.js' does not provide an export named 'extractGlobal'
    at async <anonymous>:2:38
```

this happens because `https://esm.sh/@polkadot/x-global?pin=v60` is null for some reason.

**Comment by talentlessguy** [comment]
on v74:

```
error: Uncaught SyntaxError: Detected cycle while resolving name 'Keyring' in '/v74/@polkadot/keyring@8.7.1/deno/keyring.js'
    at <anonymous> (https://cdn.esm.sh/v74/@polkadot/keyring@8.7.1/deno/bundle.js:2:8)
```

**Comment by talentlessguy** [comment]
it works on v135

```js
> import { ApiPromise, WsProvider } from "https://esm.sh/@polkadot/api";
undefined
> ApiPromise
[class t extends n]
> WsProvider
[class l]

```
