### ISSUE TITLE
Failed to import - cloudinary

### ISSUE THREAD

**Issue by aiotter** [esm-dev/esm.sh#253]
## Failing module

- **GitHub**: https://github.com/cloudinary/cloudinary_npm
- **npm**: https://www.npmjs.com/package/cloudinary

```js
import * as cloudinary from "https://esm.sh/cloudinary@1.28.1?no-check";
```

## Error message

After running `deno run` I got this:

```
Download https://esm.sh/cloudinary@1.28.1?no-check
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at https://cdn.esm.sh/v63/cloudinary@1.28.1/deno/cloudinary.js:16:24037
    at https://cdn.esm.sh/v63/cloudinary@1.28.1/deno/cloudinary.js:2:2780
    at https://cdn.esm.sh/v63/cloudinary@1.28.1/deno/cloudinary.js:16:24210
```

## Additional info

- **esm.sh version**: v63
- **Deno version**: 1.17.2

When I tried to import it without `?no-check` flag, the following error occurred:
```
error: TS2671 [ERROR]: Cannot augment module 'cloudinary' because it resolves to a non-module entity.
declare module 'cloudinary' {
               ~~~~~~~~~~~~
    at https://cdn.esm.sh/v63/cloudinary@1.28.1/types/index.d.ts:4:16
```

After `import "https://deno.land/std@0.122.0/node/global.ts"`, `process.versions.node.split(".")` itself works successfully.
There seems to be a bug in node.js compartible layer in esm.sh.

**Comment by ije** [comment]
@aiotter thanks i will look into it

**Comment by ije** [comment]
after added `process.versions.node` i got anther error:

<img width="596" alt="Screenshot 2022-01-21 at 23 21 40" src="https://user-images.githubusercontent.com/2883484/150552588-2bc68d6a-b526-4f67-9e57-1e841e6c81f7.png">

**Comment by ije** [comment]
`types` seems to work for me:

<img width="885" alt="Screenshot 2022-01-21 at 23 24 15" src="https://user-images.githubusercontent.com/2883484/150553066-a4a58549-772f-46cd-bf8e-797cd6e67c0f.png">

**Comment by aiotter** [comment]
Nice, it was so quick! Thanks ☺️

**Comment by aiotter** [comment]
@ije It seems now working on both esm.sh and localhost yet.

esm.sh:
```
> import "https://esm.sh/v64/cloudinary"
Uncaught Error: Dynamic require of "proxy-agent" is not supported
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2751
    at Object.Qd [as optionalRequire] (https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:13:3076)
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:14:312
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:16:20836
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:16:24193
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at https://cdn.esm.sh/v64/cloudinary@1.28.1/deno/cloudinary.js:16:24210
```

localhost (10c10b993c9126c0f45f6f5948917ffd51ef2746):
```
> import "http://localhost:8080/cloudinary"
Uncaught Error: Dynamic require of "proxy-agent" is not supported
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2751
    at Object.Qd [as optionalRequire] (http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:13:3076)
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:14:312
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:16:20836
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:16:24193
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:2:2831
    at http://localhost:8080/v64/cloudinary@1.28.1/deno/cloudinary.js:16:24210
```

**Comment by aiotter** [comment]
@ije This is just a gentle reminder, but did you checked my report above? If this is a solvable problem on the esm.sh side, can you please reopen the issue?

**Comment by ije** [comment]
i think i can not fix it, since esbuild rewrite the `require` function. 
but i guess you can add a workaround for it:

```
import proxyAgent from "https://esm.sh/proxy-agent"
globalThis.require = (name) => {
  if (name == "proxy-agent") return proxyAgent
}

import "https://esm.sh/v64/cloudinary"
```

**Comment by ije** [comment]
same as #257

**Comment by aiotter** [comment]
Thank you for workaround! I appreciate it 😂
