### ISSUE TITLE
v64 breaks Deno bundling with protobufjs

### ISSUE THREAD

**Issue by ObsidianX** [esm-dev/esm.sh#256]
According to the changelog build v64 updated the way `process` is handled.  As a result the Deno version of `protobufjs` includes `https://deno.land/std@0.122.0/node/process.ts` which includes unstable APIs and cannot be used without adding the `--unstable` flag to all Deno commands.

---

Sample file:
```ts
// test.ts
import 'https://esm.sh/protobufjs';
```

Result:
```
$ deno cache test.ts
# ...
Check file:///tmp/test.ts
error: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'. 'Deno.setRaw' is an unstable API. Did you forget to run with the '--unstable' flag?
  Deno.setRaw?.(Deno.stdin?.rid, enable);
       ~~~~~~
    at https://deno.land/std@0.122.0/node/_process/streams.ts:65:8

TS2339 [ERROR]: Property 'addSignalListener' does not exist on type 'typeof Deno'. 'Deno.addSignalListener' is an unstable API. Did you forget to run with the '--unstable' flag?
      Deno.addSignalListener(event as Deno.Signal, listener);
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:285:12

TS2339 [ERROR]: Property 'removeSignalListener' does not exist on type 'typeof Deno'. 'Deno.removeSignalListener' is an unstable API. Did you forget to run with the '--unstable' flag?
      Deno.removeSignalListener(event as Deno.Signal, listener);
           ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:303:12

TS2339 [ERROR]: Property 'umask' does not exist on type 'typeof Deno'. 'Deno.umask' is an unstable API. Did you forget to run with the '--unstable' flag?
  umask = Deno.umask;
               ~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:384:16

Found 4 errors.
```

If `--unstable` is provided then it will succeed, but attempting to generate a CommonJS bundle from the result fails for another reason:
```
$ esbuild test.js --format=cjs --outfile=test.esbuild.js
✘ [ERROR] Top-level await is currently not supported with the "cjs" output format

    test.js:10897:13:
      10897 │     state = (await Deno.permissions.query({
            ╵              ~~~~~

1 error
```

---

Pinning version v63 fixes both of the above errors:
```ts
// test.ts
import 'https://esm.sh/protobufjs?pin=v63';
```

```
$ deno bundle test.ts -- test.js
Check file:///tmp/test.ts
Bundle file:///tmp/test.ts
Emit "test.js" (140.55KB)
$ esbuild test.js --format=cjs --outfile=test.esbuild.js

  test.esbuild.js  127.2kb

⚡ Done in 14ms
```

---

Test to verify it's the inclusion of `process`:
```ts
// test.ts
import 'https://deno.land/std@0.122.0/node/process.ts';
```

```
$ deno cache test.ts
Check file:///tmp/test.ts
error: TS2339 [ERROR]: Property 'setRaw' does not exist on type 'typeof Deno'. 'Deno.setRaw' is an unstable API. Did you forget to run with the '--unstable' flag?
  Deno.setRaw?.(Deno.stdin?.rid, enable);
       ~~~~~~
    at https://deno.land/std@0.122.0/node/_process/streams.ts:65:8

TS2339 [ERROR]: Property 'addSignalListener' does not exist on type 'typeof Deno'. 'Deno.addSignalListener' is an unstable API. Did you forget to run with the '--unstable' flag?
      Deno.addSignalListener(event as Deno.Signal, listener);
           ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:285:12

TS2339 [ERROR]: Property 'removeSignalListener' does not exist on type 'typeof Deno'. 'Deno.removeSignalListener' is an unstable API. Did you forget to run with the '--unstable' flag?
      Deno.removeSignalListener(event as Deno.Signal, listener);
           ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:303:12

TS2339 [ERROR]: Property 'umask' does not exist on type 'typeof Deno'. 'Deno.umask' is an unstable API. Did you forget to run with the '--unstable' flag?
  umask = Deno.umask;
               ~~~~~
    at https://deno.land/std@0.122.0/node/process.ts:384:16

Found 4 errors.
```

**Comment by Xeevis** [comment]
I think I also have problem with mentioned change, this works fine
```ts
import mapboxgl from "https://esm.sh/mapbox-gl@2.6.1?pin=v63";
```
but this throws
```ts
import mapboxgl from "https://esm.sh/mapbox-gl@2.6.1?pin=v64";
```

```ps
X [ERROR] Expected "from" but found "{"

    deno-url:https://deno.land/std@0.122.0/node/process.ts:36:12:       
      36 │ import type { BindingName } from "./internal_binding/mod.ts";
         │             ^
         ╵             from

fatal error: error: Uncaught (in promise) Error: Build failed with 1 error:
deno-url:https://deno.land/std@0.122.0/node/process.ts:36:12: ERROR: Expected "from" but found "{"
  let error = new Error(`${text}${summary}`);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.13/mod.js:1521:15)
    at https://deno.land/x/esbuild@v0.14.13/mod.js:1179:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.13/mod.js:967:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.13/mod.js:1177:7)
    at https://deno.land/x/esbuild@v0.14.13/mod.js:1286:14
    at https://deno.land/x/esbuild@v0.14.13/mod.js:599:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.13/mod.js:696:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.13/mod.js:566:7)
    at https://deno.land/x/esbuild@v0.14.13/mod.js:1794:11
The terminal process "C:\Users\Xeevis\.dev\deno.EXE 'run', '--allow-all', '--unstable', 'build.ts'" terminated with exit code: 1.
```

**Comment by ije** [comment]
if you are bundling code for browsers or nodejs, try to use https://esm.sh/PACKAGE?target=2021 instead

**Comment by ObsidianX** [comment]
Swapping
```ts
import 'https://esm.sh/protobufjs?pin=v63';
```
to
```ts
import 'https://esm.sh/protobufjs?target=2021';
```
Produces the same problems as before.  `https://deno.land/std@0.122.0/node/process.ts` is still included.

**Comment by Xeevis** [comment]
Same issue here as well. @ije should the query string take absolute priority? Because it appears that is not the case. Deno will cache "deno production" build every single time from within VS Code, `?target` makes no difference whatsoever.

```diff
Starting Deno language server...
  version: 1.18.0 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\Xeevis\.dev\deno.EXE
Connected to "Visual Studio Code" 1.63.2
Enabling import suggestions for: https://deno.land
Enabling import suggestions for: https://x.nest.land
Download https://x.nest.land/.well-known/deno-import-intellisense.json
Download https://intellisense.nest.land/deno-import-intellisense.json
Enabling import suggestions for: https://crux.land
language server initialized
Server ready.
+ Download https://esm.sh/mapbox-gl@2.6.1?target=es2021
- Download https://cdn.esm.sh/v64/mapbox-gl@2.6.1/deno/mapbox-gl.js
Download https://cdn.esm.sh/v64/@types/mapbox-gl@2.6.0/index.d.ts
Download https://deno.land/std@0.122.0/node/process.ts
Download https://cdn.esm.sh/v64/@types/geojson@7946.0.8/index.d.ts
Download https://deno.land/std@0.122.0/node/_errors.ts
Download https://deno.land/std@0.122.0/node/_options.ts
```

**Comment by ije** [comment]
sorry, my mistake! please use `?target=es2015` to `?target=es2021`

```ts
import 'https://esm.sh/protobufjs?target=es2021';
```

**Comment by Xeevis** [comment]
> sorry, my mistake! please use `?target=es2015` to `?target=es2021`
> 
> ```ts
> import 'https://esm.sh/protobufjs?target=es2021';
> ```

It loads es2021 now, but I've also lost intellisense, with `?target=es2021` it's not downloading any types unlike `?target=deno` any way to solve this?
