### ISSUE TITLE
Failed to import - io-ts (sub-modules)

### ISSUE THREAD

**Issue by MichaelHirn** [esm-dev/esm.sh#286]
## Failing module

- **GitHub**: https://github.com/gcanti/io-ts
- **npm**: https://www.npmjs.com/package/io-ts

#274 fixed importing the `io-ts/index.ts`, however due to architecture of the library almost everyone needs to import one of it's submodules, e.g. `io-ts/Type` which does not yet work.

```js
import * as T from 'https://esm.sh/io-ts/Type'
```

I created a repo with test files to reproduce error [here](https://github.com/MichaelHirn/esm-issue-274).

## Error message

After running `deno run` I got this:

```
error: TS2370 [ERROR]: A rest parameter must be of an array type.
    ...components: {
    ^
    at https://cdn.esm.sh/v72/io-ts@2.2.16/lib/Schemable.d.ts:63:5

TS2370 [ERROR]: A rest parameter must be of an array type.
    ...components: {
    ^
    at https://cdn.esm.sh/v72/io-ts@2.2.16/lib/Schemable.d.ts:124:5

TS2370 [ERROR]: A rest parameter must be of an array type.
    ...components: {
    ^
    at https://cdn.esm.sh/v72/io-ts@2.2.16/lib/Schemable.d.ts:188:5

Found 3 errors.
```

## Additional info

- **esm.sh version**: 72
- **Deno version**: 1.20.1

**Comment by ije** [comment]
oh, i will take a look

**Comment by MichaelHirn** [comment]
may or may not be related to #342
