### ISSUE TITLE
Failed to import - discord.js

### ISSUE THREAD

**Issue by DerTev** [esm-dev/esm.sh#294]
## Failing module

- **GitHub**: https://github.com/discordjs/discord.js
- **npm** :https://www.npmjs.com/package/discord.js

```ts
import { Client, Intents } from "https://esm.sh/discord.js"
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://cdn.esm.sh/v74/discord-api-types@0.26.1/deno/rpc/v9.js' failed: 500 Internal Server Error
    at https://cdn.esm.sh/v74/discord-api-types@0.26.1/deno/v9.js:2:425
```

## Additional info

- **Deno version**: 1.20.4 (release, x86_64-unknown-linux-gnu)

**Comment by talentlessguy** [comment]
New error:

```
import { Client, Intents } from "https://esm.sh/discord.js"
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:zlib-sync@0.1.9
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
Uncaught TypeError: The URL must be of scheme file
    at fileURLToPath (node:url:1160:11)
    at getFilename (https://esm.sh/v135/@discordjs/ws@1.1.1/denonext/ws.mjs:2:3035)
    at getDirname (https://esm.sh/v135/@discordjs/ws@1.1.1/denonext/ws.mjs:2:3087)
```
