### ISSUE TITLE
Failed to import - css-in-js-utils

### ISSUE THREAD

**Issue by ChristopherHaws** [esm-dev/esm.sh#305]
Hello,

I am trying to import `@fluentui/react-northstar` which has a chain of dependencies, one of which is `css-in-js-utils` which is failing to import when I run `aleph dev`.

## Failing module

- **GitHub**: https://github.com/robinweser/css-in-js-utils
- **npm**: https://www.npmjs.com/package/css-in-js-utils

```js
import { Button } from 'https://esm.sh/@fluentui/react-northstar@0.62.0'
```

## Error message

After running `aleph dev` I got this:

```
INFO Download https://cdn.esm.sh/v77/css-in-js-utils@3.1.0/deno/lib/assignStyle.development.js
 > https://cdn.esm.sh/v77/css-in-js-utils@3.1.0/deno/lib/cssifyDeclaration.development.js:74:2: error: The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)
    74 │   __esModule,
       ╵   ~~~~~~~~~~

error: Uncaught (in promise) Error: Build failed with 1 error:
https://cdn.esm.sh/v77/css-in-js-utils@3.1.0/deno/lib/cssifyDeclaration.development.js:74:2: error: The export name "__esModule" is reserved and cannot be used (it's needed as an export marker when converting ES module syntax to CommonJS)
  let error = new Error(`${text}${summary}`);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.13.2/mod.js:1439:15)
    at https://deno.land/x/esbuild@v0.13.2/mod.js:1097:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.13.2/mod.js:885:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.13.2/mod.js:1095:7)
    at https://deno.land/x/esbuild@v0.13.2/mod.js:1204:14
    at https://deno.land/x/esbuild@v0.13.2/mod.js:573:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.13.2/mod.js:670:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.13.2/mod.js:540:7)
    at https://deno.land/x/esbuild@v0.13.2/mod.js:1709:11
```

## Additional info

- **esm.sh version**: V77
- **Deno version**: v1.20.6

**Comment by talentlessguy** [comment]
it works on latest v135

```
> import { Button } from 'https://esm.sh/@fluentui/react-northstar@0.62.0'
undefined
> Button
{
  "$$typeof": Symbol(react.forward_ref),
  render: [Function (anonymous)],
  displayName: "Button",
  fluentComposeConfig: {
    className: "ui-button",
    classes: [ undefined ],
    displayName: "Button",
    displayNames: [ "Button" ],
```
