### ISSUE TITLE
[react@18.1.0] Subsequent property declarations must have the same type

### ISSUE THREAD

**Issue by ynwd** [esm-dev/esm.sh#321]
OK if use:

`https://esm.sh/react-dom@17.0.2/server`
`https://esm.sh/react@17.0.2`

Got error if use:

`https://esm.sh/react-dom@18.1.0/server`
`https://esm.sh/react@18.1.0`

```
...
TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'link' must be of type 'DetailedHTMLProps<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>', but here has type 'DetailedHTMLProps<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>'.
            link: React.DetailedHTMLProps<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
            ~~~~
    at https://cdn.esm.sh/v78/@types/react@18.0.8/index.d.ts:3196:13

    'link' was also declared here.
                link: React.DetailedHTMLProps<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
                ~~~~
        at https://cdn.esm.sh/v78/@types/react@18.0.6/index.d.ts:3192:13

Found 3 errors.
```

**Comment by ynwd** [comment]
resolved after add typings:
```
// @deno-types="https://cdn.esm.sh/v77/@types/react@18.0.9/react.d.ts"
import React from "https://esm.sh/react@18.1.0";
```
