### ISSUE TITLE
Failed to import - rollup-plugin-jscc since v75

### ISSUE THREAD

**Issue by jespertheend** [esm-dev/esm.sh#423]
## Failing module

- **GitHub**: https://github.com/aMarCruz/rollup-plugin-jscc
- **npm**: https://www.npmjs.com/package/rollup-plugin-jscc

```js
import jscc from "https://esm.sh/rollup-plugin-jscc@2.0.0?pin=v75";

jscc();
```

## Error message

After running `deno run --allow-env --allow-read jscctest.js` I got this:

```
error: Uncaught TypeError: F is not a function
    at y (https://esm.sh/v75/rollup-plugin-jscc@2.0.0/deno/rollup-plugin-jscc.js:2:1931)
    at h (https://esm.sh/v75/rollup-plugin-jscc@2.0.0/deno/rollup-plugin-jscc.js:2:2501)
    at file:///Users/Jesper/game-engine/jscctest.js:3:1
```

## Additional info

- **esm.sh version**: `v75` and up, `v74` doesn't seem to have this issue
- **Deno version**: `1.25.4`

**Comment by talentlessguy** [comment]
works on v135:

```
import jscc from "https://esm.sh/rollup-plugin-jscc@2.0.0";

jscc();
[npm] deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
{ name: "jscc", load: [Function: load] }
```
