### ISSUE TITLE
Failed to import jsdom - if html has img tag

### ISSUE THREAD

**Issue by zuisong** [esm-dev/esm.sh#482]
## Failing module

- **GitHub**: 
- **npm**: jsdom

```ts
import { JSDOM } from "https://esm.sh/jsdom@20.0.3?pin=v102&dev&bundle";

const { window: { document } } = new JSDOM(
  `<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hello from Deno</title>
  </head>
  <body>
    <img src="https://picsum.photos/200/300" />
  </body>
</html>`
);

```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: Canvas.Image is not a constructor
          this._image = new Canvas.Image();
                        ^
    at HTMLImageElementImpl._updateTheImageData (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:78594:25)
    at HTMLImageElementImpl._attrModified (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:78553:16)
    at Object.exports.appendAttribute (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:33231:15)
    at Object.exports.setAttributeValue (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:33359:17)
    at JSDOMParse5Adapter.adoptAttributes (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:50240:22)
    at JSDOMParse5Adapter.createElement (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:50179:14)
    at Parser._appendElement (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:47133:42)
    at areaStartTagInBody (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:48510:9)
    at startTagInBody (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:48686:11)
    at Parser._startTagOutsideForeignContent (https://esm.sh/v102/jsdom@20.0.3/deno/jsdom.development.bundle.js:47648:13)
```

## Additional info

- **esm.sh version**: v102
- **Deno version**: 1.29.1

**Comment by bvpav** [comment]
Ran into the same issue as well, it appears as if it works perfectly fine when jsdom is imported with an npm specifier, but fails when using esm.sh.
I prepared [a Dockerfile](https://gist.github.com/bvpav/23049db5d9fcc29ceb18c8fbcc2a4d8b) that sets this error up.
