### ISSUE TITLE
Failed to import graphql - library seems to be completely broken

### ISSUE THREAD

**Issue by jtiai** [esm-dev/esm.sh#547]
## Failing module

- **GitHub**: 
- **npm**: graphql

```js
import { GraphQLError } from 'https://esm.sh/graphql@16.6.0/graphql'
```

## Error message

After running `deno run` I got this:

```
error: Uncaught SyntaxError: The requested module '/v111/graphql@16.6.0/deno/graphql.js' does not provide an export named 'GraphQLError'
```

## Additional info

- **esm.sh version**: No idea.
- **Deno version**:
deno 1.31.2 (release, aarch64-apple-darwin)
v8 11.0.226.19
typescript 4.9.4

Module used to work until about 8th of March 2023. After that Deno actually complained about hash change and after reloading everything error started to appear.

**Comment by Justinidlerz** [comment]
Hi @jtiai , Seems the https://unpkg.com/graphql@16.6.0/graphql.js file has not exported the `GraphQLError` module.
In your case, you should use to instead.
```
import { GraphQLError } from 'https://esm.sh/graphql@16.6.0/index'
```
hope can help you.  : )

**Comment by jtiai** [comment]
> Hi @jtiai , Seems the https://unpkg.com/graphql@16.6.0/graphql.js file has not exported the `GraphQLError` module. In your case, you should use to instead.
> 
> ```
> import { GraphQLError } from 'https://esm.sh/graphql@16.6.0/index'
> ```
> 
> hope can help you. : )

The catch is that plain graphql import is being widely used by many 3rd party packages which I can't change.

**Comment by Justinidlerz** [comment]
> The catch is that plain graphql import is being widely used by many 3rd party packages which I can't change.

Okay, I found the problem that is due to an import file conflict, fixing it.

**Comment by Justinidlerz** [comment]
@jtiai We has been fixed the entry point bug, could you please try again?
 The pin `v112` will resolve the import path to 
`https://esm.sh/graphql@16.6.0` to `https://esm.sh/v112/graphql@16.6.0/es2022/graphql.mjs` and export some correct modules.
![image](https://user-images.githubusercontent.com/7475347/227079421-f4b7afc8-1c30-4347-80b4-d0a32baeb0cd.png)

**Comment by Justinidlerz** [comment]
@jtiai Could you please share your full use case?

**Comment by jtiai** [comment]
This is MVP which triggers the error:
```typescript
import { GraphQLScalarType, ValueNode } from "https://esm.sh/graphql@16.6.0/type/index.mjs";
import { Kind } from "https://esm.sh/graphql@16.6.0/language/kinds.mjs";

const dateTimeScalar = new GraphQLScalarType({
  name: "DateTime",
  description: "Date and time scalar type",
  serialize(value: unknown): string {
      return (value as string); // REST API sends timestamps as ISO strings already
  },
  parseValue(value: unknown): Date {
      return new Date(value as string); // Convert ISO date string to Date
  },
  parseLiteral(ast: ValueNode): Date | null {
      if (ast.kind === Kind.STRING) {
          return new Date(ast.value); // Do not change incoming string
      }
      return null; // Something fishy
  },
});
```

**Comment by ije** [comment]
@jtiai please remove `.mjs` extension of your imports, we will fix this later

```ts
import { GraphQLScalarType, ValueNode } from "https://esm.sh/graphql@16.6.0/type/index";
import { Kind } from "https://esm.sh/graphql@16.6.0/language/kinds";
```

**Comment by talentlessguy** [comment]
This happens on v130 when importing different parts of graphql:

```
error: Error: Cannot use GraphQLSchema "{ __validationErrors: undefined, description: undefined, extensions: {}, astNode: undefined, extensionASTNodes: [], _queryType: Query, _mutationType: undefined, _subscriptionType: undefined, _directives: [@include, @skip, @deprecated, @specifiedBy], _typeMap: { Query: Query, String: String, Boolean: Boolean, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind, __Field: __Field, __InputValue: __InputValue, __EnumValue: __EnumValue, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation }, _subTypeMap: {}, _implementationsMap: {} }" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at Y (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:12:2032)
    at ji (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:52:8341)
    at rr (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:52:8368)
    at tn (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:52:11885)
    at si (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:54:50300)
    at https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:54:49916
    at new Promise (<anonymous>)
    at hd (https://esm.sh/v130/graphql@16.7.1/denonext/graphql.js:54:49899)
    at runHttpQuery (file:///home/v1rtl/Coding/gql/common.ts:28:16)
    at ItNode.fn (file:///home/v1rtl/Coding/gql/mod_test.ts:277:26)
```
