### ISSUE TITLE
Failed to import - asciidoctor@3.0.0-alpha.4

### ISSUE THREAD

**Issue by taind772** [esm-dev/esm.sh#557]
## Failing module asciidoctor@3.0.0-alpha.4

- **GitHub**:  https://github.com/asciidoctor/asciidoctor.js
- **npm**: https://www.npmjs.com/package/asciidoctor/v/3.0.0-alpha.4

```js
import {Asciidoctor} from 'https://esm.sh/asciidoctor@3.0.0-alpha.4'

console.log(Asciidoctor);
```

## Error message

After running `deno run` I got this:

```
error: Uncaught SyntaxError: The requested module 'https://esm.sh/v111/asciidoctor@3.0.0-alpha.4' does not provide an export named 'Asciidoctor'
import {Asciidoctor} from 'https://esm.sh/v111/asciidoctor@3.0.0-alpha.4'
        ^
    at <anonymous> (file:///home/taind/code/personal/blogs/src/test.ts:1:9)
```

## Additional info

- **esm.sh version**: v111
- **Deno version**:  v1.31.2

Something like 
```js
import * as adoc from 'https://esm.sh/v111/asciidoctor@3.0.0-alpha.4'

console.log(adoc.default.default);
```
worked:
```
❯ deno run src/test.ts
[Function: Qt]
```
, but Deno lsp wasn't happy with it:
![image](https://user-images.githubusercontent.com/49815011/226668224-45576227-10bc-4d19-965a-a72669d2ad77.png)

**Comment by taind772** [comment]
Thank you for your hard work, the above example work now :1st_place_medal: 

I'm now able to use the Asciidoctor package, but some bugs are still annoying me: 
```
import { Asciidoctor } from "https://esm.sh/v113/asciidoctor@3.0.0-alpha.4";

const asciidoctor = new Asciidoctor();

console.log(asciidoctor);
```
After running `deno run` I got this:

```
❯ deno run -A src/main.ts
error: Uncaught SyntaxError: The requested module 'https://esm.sh/v113/asciidoctor@3.0.0-alpha.4' does not provide an export named 'Asciidoctor'
import { Asciidoctor } from "https://esm.sh/v113/asciidoctor@3.0.0-alpha.4";
         ^
    at <anonymous> (file:///.../src/main.ts:1:10)
```

but actually, it did provide an export class name Asciidoctor:
![image](https://user-images.githubusercontent.com/49815011/227760457-a6f6bf1e-12a7-4d87-862f-d2baa63320e7.png)
