### ISSUE TITLE
Failed to import - @zondax/ledger-substrate@0.40.6 (git+ssh checkout failure on esm.sh)

### ISSUE THREAD

**Issue by jacogr** [esm-dev/esm.sh#585]
## Failing module

- **GitHub**: https://github.com/Zondax/ledger-substrate-js
- **npm**: https://www.npmjs.com/package/@zondax/ledger-substrate

```js
// https://esm.sh/@zondax/ledger-substrate@0.40.6
import X from "https://esm.sh/@zondax/ledger-substrate@0.40.6"
```

## Error message

After running `deno run` I got this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "pnpm add @zondax/ledger-substrate@0.40.6:  ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/Zondax/bip32-ed25519.git HEAD
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

This error happened while installing the dependencies of @zondax/ledger-substrate@0.40.6

pnpm: Command failed with exit code 128: git ls-remote git+ssh://git@github.com/Zondax/bip32-ed25519.git HEAD
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:24235:17)
    at handlePromise (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:24806:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getRepoRefs (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:110413:23)
    at async resolveRef (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:110425:20)
    at async resolveGit (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:110376:24)
    at async Object.resolve (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:112947:173)
    at async run (/etc/esmd/nodejs/lib/node_modules/pnpm/dist/pnpm.cjs:124722:23)\n");
export default null;
```

It originates from here - https://github.com/Zondax/ledger-substrate-js/blob/main/package.json#L33

Note that this was working a short while ago - it is quite possibly related to the GH ssh changes recently.

## Additional info

- **esm.sh version**:
- **Deno version**:

**Comment by jacogr** [comment]
Seems the linked issue (which resulted in a repo rename), fixed the issue, aka https://esm.sh/@zondax/ledger-substrate@0.40.6 works again.

Closing.
