### ISSUE TITLE
Failed to import - @sendgrid/mail@7.7.0

### ISSUE THREAD

**Issue by FranckPoingt** [esm-dev/esm.sh#605]
## Failing module

- **GitHub**: https://github.com/sendgrid/sendgrid-nodejs/tree/main/packages/mail
- **npm**: https://www.npmjs.com/package/@sendgrid/mail

```js
import sgMail from "https://esm.sh/@sendgrid/mail@7.7.0";
```

## Error message

After running `supabase functions deploy  myFn`  I got this:

```
Error: Error bundling function: exit status 1
file:///src/import_map.json
file:///src/index.ts
error: Uncaught (in promise) Error: Relative import path "https" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v117/@types/node@18.15.13/https.d.ts"
      const ret = new Error(getStringFromWasm0(arg0, arg1));
                  ^
    at __wbg_new_8d2af00bc1e329ee (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:312:19)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:79439)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1388039)
    at <anonymous> (https://deno.land/x/eszip@v0.30.0/eszip_wasm_bg.wasm:1:1862894)
    at __wbg_adapter_18 (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:146:6)
    at real (https://deno.land/x/eszip@v0.30.0/eszip_wasm.generated.js:130:14)

```

## Additional info

- **esm.sh version**: v117
- **Deno version**: 1.32.4

**Comment by ije** [comment]
<img width="747" alt="Screenshot 2023-04-23 at 19 37 18" src="https://user-images.githubusercontent.com/2883484/233837527-678d1e1c-232f-4d85-a8ec-585d7a7da00b.png">
seems it works locally, maybe it's a bug of deno deploy.

**Comment by FranckPoingt** [comment]
@ije I gave up on using the package and went for wretch and a simple post to the API endpoint.

Thanks for testing it
