### ISSUE TITLE
Failed to import - geojson-rbush

### ISSUE THREAD

**Issue by diachedelic** [esm-dev/esm.sh#620]
## Failing module

- **GitHub**: https://github.com/DenisCarriere/geojson-rbush
- **npm**: https://npmjs.com/package/geojson-rbush

```js
import rbush from "https://esm.sh/geojson-rbush";
```

## Error message
```
ReferenceError: __1$default is not defined
    at https://esm.sh/v118/geojson-rbush@3.2.0/es2022/geojson-rbush.mjs:2:1256
    at https://esm.sh/v118/geojson-rbush@3.2.0/es2022/geojson-rbush.mjs:2:794
    at https://esm.sh/v118/geojson-rbush@3.2.0/es2022/geojson-rbush.mjs:2:2771
```

## Additional info

I was previously pinning esm.sh to v113, the last version to correctly import this package, but it seems that pinning to v113 no longer has any effect.

- **esm.sh version** v118:
- **Browser version** Chrome v112:

**Comment by diachedelic** [comment]
Thanks!
