### ISSUE TITLE
Failed to import - pako@1.0.11

### ISSUE THREAD

**Issue by park-brian** [esm-dev/esm.sh#628]
## Failing module pako@1.0.11

- **GitHub**: https://github.com/nodeca/pako/tree/1.0.11
- **npm**: https://www.npmjs.com/package/pako/v/1.0.11

```js
import { Inflate, Z_SYNC_FLUSH } from "https://esm.sh/v120/pako@1.0.11/es2022/pako.mjs?cjs-exports=Inflate,Z_SYNC_FLUSH";
console.log(Inflate, Z_SYNC_FLUSH);
```

## Error message
After `onload` I got this error:

```
Uncaught SyntaxError: The requested module 'https://esm.sh/v120/pako@1.0.11/es2022/pako.mjs?cjs-exports=Inflate,Z_SYNC_FLUSH' does not provide an export named 'Inflate'
```

## Additional info
The following code works. Unfortunately I do not have access to change this import, as it is in a sub-dependency of a library. Thank you for your help!

```js
import * as Pako from "https://esm.sh/v120/pako@1.0.11/es2022/pako.mjs";
console.log(Pako.default.Inflate, Pako.default.Z_SYNC_FLUSH);
```

- **esm.sh version**: v120
- **Browser version**: Edge 113.0.1774.35/Chrome 113.0.5672.92

**Comment by park-brian** [comment]
We can see an example of this issue in the following import: 

```html
<script src="https://esm.sh/v120/@gmod/bgzf-filehandle@1.4.5/es2022/bgzf-filehandle.mjs" type="module"></script>
```

```js
/* esm.sh - esbuild bundle(@gmod/bgzf-filehandle@1.4.5) es2022 production */
import { Buffer as __Buffer$ } from "/v120/buffer@6.0.3/es2022/buffer.bundle.mjs";
import { Z_SYNC_FLUSH as k, Inflate as y } from "/v120/pako@1.0.11/es2022/pako.mjs";
```

Error
```
Uncaught SyntaxError: The requested module '/v120/pako@1.0.11/es2022/pako.mjs' does not provide an export named 'Z_SYNC_FLUSH' (at bgzFilehandle.ts:130:3)
```

**Comment by ije** [comment]
please use `import { Inflate, Z_SYNC_FLUSH } from "https://esm.sh/v120/pako@1.0.11?cjs-exports=Inflate,Z_SYNC_FLUSH"` instead
<img width="572" alt="Screenshot 2023-05-13 at 13 42 11" src="https://github.com/esm-dev/esm.sh/assets/2883484/3bbfcfa7-f99f-4385-a2e0-59fa9a7950ba">

**Comment by ije** [comment]
> We can see an example of this issue in the following import:
> 
> ```
> <script src="https://esm.sh/v120/@gmod/bgzf-filehandle@1.4.5/es2022/bgzf-filehandle.mjs" type="module"></script>
> ```
> 
> ```js
> /* esm.sh - esbuild bundle(@gmod/bgzf-filehandle@1.4.5) es2022 production */
> import { Buffer as __Buffer$ } from "/v120/buffer@6.0.3/es2022/buffer.bundle.mjs";
> import { Z_SYNC_FLUSH as k, Inflate as y } from "/v120/pako@1.0.11/es2022/pako.mjs";
> ```
> 
> Error
> 
> ```
> Uncaught SyntaxError: The requested module '/v120/pako@1.0.11/es2022/pako.mjs' does not provide an export named 'Z_SYNC_FLUSH' (at bgzFilehandle.ts:130:3)
> ```

i will fix this

**Comment by park-brian** [comment]
Thank you, I really appreciate it

**Comment by park-brian** [comment]
For now, I am using an import map to work around this issue:

```html
<script type="importmap">
  {
    "imports": {
      "https://esm.sh/v120/pako@1.0.11/es2022/pako.mjs": "https://esm.sh/pako@1.0.11?cjs-exports=Inflate,Z_SYNC_FLUSH&exports=Inflate,Z_SYNC_FLUSH"
    }
  }
</script>
```

**Comment by ije** [comment]
@park-brian v121 should work fine

**Comment by ije** [comment]
free to open this if not work for you thanks!

**Comment by park-brian** [comment]
Great, thank you so much!
