### ISSUE TITLE
Failed to import -  https://esm.sh/pusher@5.1.2

### ISSUE THREAD

**Issue by fro-profesional** [esm-dev/esm.sh#649]
## Failing module

- **GitHub**: https://dash.deno.com/playground/paco-dev
- **npm**: https://npmjs.com/package/pusher

```js
import Pusher from "https://esm.sh/pusher@5.1.2";
```

## Error message

After running `deno run` I got this:

```
Trace: TypeError: je is not a function
    at Object.He [as send] (https://esm.sh/v119/pusher@5.1.2/deno/pusher.mjs:2:5690)
    at i.post (https://esm.sh/v119/pusher@5.1.2/deno/pusher.mjs:3:6380)
    at Object.q.trigger (https://esm.sh/v119/pusher@5.1.2/deno/pusher.mjs:2:3699)
    at i.trigger (https://esm.sh/v119/pusher@5.1.2/deno/pusher.mjs:3:6148)
    at doPusher (file:///Users/franciscoramos/Documents/clau/code/clau/test.js:17:33)
    at file:///Users/franciscoramos/Documents/clau/code/clau/test.js:28:17
    at Hono.dispatch (https://deno.land/x/hono@v3.1.6/hono.ts:241:15)
    at Server.fetch (https://deno.land/x/hono@v3.1.6/hono.ts:298:17)
    at Server.#respond (https://deno.land/std@0.183.0/http/server.ts:299:37)
    at Server.#serveHttp (https://deno.land/std@0.183.0/http/server.ts:346:20)
    at Hono.errorHandler (https://deno.land/x/hono@v3.1.6/hono.ts:55:11)
    at Hono.handleError (https://deno.land/x/hono@v3.1.6/hono.ts:211:19)
    at https://deno.land/x/hono@v3.1.6/hono.ts:268:23
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async Server.#respond (https://deno.land/std@0.183.0/http/server.ts:299:18)
```

## Additional info

- **esm.sh version**:
- **Deno version**:

**Comment by fro-profesional** [comment]
Some times it works some times it fails

**Comment by fro-profesional** [comment]
https://github.com/denoland/deploy_feedback/issues/350

**Comment by fro-profesional** [comment]
> Hi there I have an api that was working just fine not sure what happen but new deployments are not working, on my local works, and the deployment from 5 days ago works, but any new deployment don't
> 
> I'm using the pusher library with esm.sh, just wonder if anything changed recently 👀
> 
> I mean the deployment works** but the endpoint don't not sure why we didn't change the code
> 
> - clau-platform-api-scjgw1efdwxg.deno.dev/pusher doesnt work
> - clau-platform-api-renyce2zgbr0.deno.dev/pusher it works
> 
> Not code change 2-3 days apart, no new deployment is working since then
> Code
> 
> ```
> import { Router } from "oak";
> import { logger } from "../utils/logger.ts";
> import { pusher } from "../modules/pusher.ts";
> import { getFakeName } from "../tests/faker.ts";
> 
> const pusherRouter = new Router();
> 
> pusherRouter.all("/pusher", async (ctx) => {
>   let pResponse = null;
> 
>   try {
>     let name = await getFakeName();
> 
>     const date = new Date();
>     const options: any = {
>       year: "numeric",
>       month: "2-digit",
>       day: "2-digit",
>       hour: "2-digit",
>       minute: "2-digit",
>       second: "2-digit",
>       fractionalSecondDigits: 3,
>     };
>     const mexicanDate = date.toLocaleString("es-MX", options);
> 
>     pResponse = await pusher.trigger("chat-room", "new-message", {
>       message: Hi from ${name} at ${mexicanDate},
>     });
> 
>     pResponse = await pResponse.json();
>     logger.info({ pResponse });
>   } catch (error) {
>     pResponse = error;
>     logger.error({ pResponse });
>   }
> 
>   ctx.response.body = {
>     pResponse,
>   };
> });
> 
> export { pusherRouter };
> ```

**Comment by ije** [comment]
@fro-profesional just fixed, will deploy the patch later

**Comment by fro-profesional** [comment]
@ije thanks!

**Comment by ije** [comment]
v125 has been deployed, you may need to redeploy. if it still does not work please let me know, thanks
