### ISSUE TITLE
Failed to import - @slack/web-api

### ISSUE THREAD

**Issue by ekiwi111** [esm-dev/esm.sh#652]
## Failing module

- **GitHub**: https://github.com/slackapi/node-slack-sdk
- **npm**: https://www.npmjs.com/package/@slack/web-api

```js
import { WebClient } from "https://esm.sh/@slack/web-api";
```

## Error message

After running `deno run` I got this:

```
worker "/home/deno/functions/function" returned an error: Import 'https://esm.sh/@slack/web-api@6.8.1' failed: 408 Request Timeout
```

## Additional info

- **esm.sh version**: how to check this in supabase local devleopment?
- **Deno version**: how to check this in supabase local devleopment?

**Comment by ekiwi111** [comment]
Made it work with:
```
import { WebClient } from "https://esm.sh/v125/@slack/web-api@6.8.1";
```

But then:
```
Download https://esm.sh/v125/@slack/web-api@6.8.1
Download https://esm.sh/v125/@slack/web-api@6.8.1/esnext/web-api.mjs
Download https://esm.sh/v125/stream-browserify@3.0.0/esnext/stream-browserify.bundle.mjs
Download https://esm.sh/v125/util@0.12.5/esnext/util.bundle.mjs
Download https://esm.sh/v125/browserify-zlib@0.2.0/esnext/browserify-zlib.bundle.mjs
Download https://esm.sh/v125/is-electron@2.2.0/esnext/is-electron.mjs
Download https://esm.sh/v125/form-data@2.5.1/esnext/form-data.mjs
Download https://esm.sh/v125/axios@0.27.2/esnext/axios.mjs
Download https://esm.sh/v125/is-stream@1.1.0/esnext/is-stream.mjs
Download https://esm.sh/v125/querystring-es3@0.2.1/esnext/querystring-es3.bundle.mjs
Download https://esm.sh/v125/path-browserify@1.0.1/esnext/path-browserify.bundle.mjs
Download https://esm.sh/v125/os-browserify@0.3.0/esnext/browser.bundle.js
Download https://esm.sh/v125/@slack/types@2.8.0/esnext/types.mjs
Download https://esm.sh/v125/eventemitter3@3.1.2/esnext/eventemitter3.mjs
Download https://esm.sh/v125/@slack/logger@3.0.0/esnext/logger.mjs
Download https://esm.sh/v125/inherits@2.0.4/esnext/inherits.mjs
Download https://esm.sh/v125/is-typed-array@1.1.10/esnext/is-typed-array.mjs
Download https://esm.sh/v125/which-typed-array@1.1.9/esnext/which-typed-array.mjs
Download https://esm.sh/v125/is-generator-function@1.0.10/esnext/is-generator-function.mjs
Download https://esm.sh/v125/is-arguments@1.1.1/esnext/is-arguments.mjs
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/pipeline.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/end-of-stream.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/_stream_passthrough.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/_stream_transform.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/_stream_duplex.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/_stream_writable.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/_stream_readable.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/constants.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/inflate.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/deflate.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/zstream.js
Download https://esm.sh/v125/assert@2.0.0/esnext/assert.bundle.mjs
Download https://esm.sh/v125/call-bind@1.0.2/esnext/callBound.js
Download https://esm.sh/v125/has-tostringtag@1.0.0/esnext/shams.js
Download https://esm.sh/v125/gopd@1.0.1/esnext/gopd.mjs
Download https://esm.sh/v125/available-typed-arrays@1.0.5/esnext/available-typed-arrays.mjs
Download https://esm.sh/v125/for-each@0.3.3/esnext/for-each.mjs
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/errors-browser.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/state.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/destroy.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/stream.js
Download https://esm.sh/v125/util-deprecate@1.0.2/esnext/util-deprecate.mjs
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/from.js
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/async_iterator.js
Download https://esm.sh/v125/string_decoder@1.3.0/esnext/string_decoder.bundle.mjs
Download https://esm.sh/v125/readable-stream@3.6.2/esnext/lib/internal/streams/buffer_list.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/inftrees.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/inffast.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/crc32.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/adler32.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/utils/common.js
Download https://esm.sh/v125/is-nan@1.3.2/esnext/is-nan.mjs
Download https://esm.sh/v125/object-is@1.1.5/esnext/object-is.mjs
Download https://esm.sh/v125/es6-object-assign@1.1.0/esnext/es6-object-assign.mjs
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/messages.js
Download https://esm.sh/v125/pako@1.0.11/esnext/lib/zlib/trees.js
Download https://esm.sh/v125/function-bind@1.1.1/esnext/function-bind.mjs
Download https://esm.sh/v125/get-intrinsic@1.2.1/esnext/get-intrinsic.mjs
Download https://esm.sh/v125/is-callable@1.2.7/esnext/is-callable.mjs
Download https://esm.sh/v125/has-symbols@1.0.3/esnext/shams.js
Download https://esm.sh/v125/stream@0.0.2/esnext/stream.mjs
Download https://esm.sh/v125/call-bind@1.0.2/esnext/call-bind.mjs
Download https://esm.sh/v125/define-properties@1.2.0/esnext/define-properties.mjs
Download https://esm.sh/v125/safe-buffer@5.2.1/esnext/safe-buffer.mjs
Download https://esm.sh/v125/has-proto@1.0.1/esnext/has-proto.mjs
Download https://esm.sh/v125/emitter-component@1.1.1/esnext/emitter-component.mjs
Download https://esm.sh/v125/has-property-descriptors@1.0.0/esnext/has-property-descriptors.mjs
Download https://esm.sh/v125/object-keys@1.1.1/esnext/object-keys.mjs
[WARN]  web-api:WebClient:0 http request failed t is not a function
TypeError: t is not a function
    at cr.exports (https://esm.sh/v125/axios@0.27.2/esnext/axios.mjs:3:6295)
    at D.request (https://esm.sh/v125/axios@0.27.2/esnext/axios.mjs:3:9775)
    at D.post (https://esm.sh/v125/axios@0.27.2/esnext/axios.mjs:3:10239)
    at Function.post (https://esm.sh/v125/axios@0.27.2/esnext/axios.mjs:2:921)
    at https://esm.sh/v125/@slack/web-api@6.8.1/esnext/web-api.mjs:4:9080
    at s (https://esm.sh/v125/p-queue@6.6.2/esnext/p-queue.mjs:2:5167)
    at m._tryToStartAnother (https://esm.sh/v125/p-queue@6.6.2/esnext/p-queue.mjs:2:4231)
    at https://esm.sh/v125/p-queue@6.6.2/esnext/p-queue.mjs:2:5393
    at new Promise (<anonymous>)
    at m.add (https://esm.sh/v125/p-queue@6.6.2/esnext/p-queue.mjs:2:5035)
```

**Comment by ekiwi111** [comment]
Never mind, made it work with the official deno port from slack.
GitHub - https://github.com/slackapi/deno-slack-api

Import as:
```
import { SlackAPI } from "https://deno.land/x/deno_slack_api@0.0.8/mod.ts";
```

**Comment by renhiyama** [comment]
@ekiwi111 but this doesn't change the fact that esm.sh failed to serve this module. I suggest opening this issue, but it's up to you & @ije

**Comment by ije** [comment]
let's open it,  I will look into it thanks 🙏
