### ISSUE TITLE
Failed to import jsbi

### ISSUE THREAD

**Issue by soilSpoon** [esm-dev/esm.sh#708]
I specified version 3, but internally it refers to version 4.

## Failing module

```js
  try {
    console.log((await import("@uniswap/smart-order-router")).AlphaRouter);
  } catch (error) {
    console.log(error);
  }
```
```json
{
  "imports": {
    "@uniswap/v3-sdk": "https://esm.sh/@mlz37/v3-sdk?external=@uniswap/sdk-core,jsbi&dev",
    "@pancakeswap/sdk": "https://esm.sh/@pancakeswap/sdk",
    "@uniswap/router-sdk": "https://esm.sh/@uniswap/router-sdk?external=@uniswap/sdk-core,@uniswap/v3-sdk&dev",
    "@uniswap/sdk-core": "https://esm.sh/@uniswap/sdk-core?external=jsbi&dev",
    "@uniswap/smart-order-router": "https://esm.sh/@uniswap/smart-order-router?external=@uniswap/router-sdk,@uniswap/v3-sdk,@uniswap/sdk-core,jsbi",
    "ethers": "https://esm.sh/ethers@5",
    "jsbi": "https://esm.sh/jsbi@^3.2.0"
  }
}

```

## Error message

After running `deno run` I got this:

```
[Info] Error: Convert JSBI instances to native numbers using `toNumber`.
    at _JSBI.valueOf (https://esm.sh/v131/jsbi@4.3.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/jsbi.development.mjs:47:11)
    at Function.__toPrimitive (https://esm.sh/v131/jsbi@3.2.5/esnext/jsbi.mjs:2:24311)
    at Function.BigInt (https://esm.sh/v131/jsbi@3.2.5/esnext/jsbi.mjs:2:714)
    at Percent2.Fraction2 (https://esm.sh/v131/@uniswap/sdk-core@4.0.6/X-ZS9qc2Jp/esnext/sdk-core.development.mjs:263:27)
    at new Percent2 (https://esm.sh/v131/@uniswap/sdk-core@4.0.6/X-ZS9qc2Jp/esnext/sdk-core.development.mjs:445:23)
    at ../esmd/npm/@uniswap/router-sdk@1.6.0/node_modules/.pnpm/@uniswap+router-sdk@1.6.0_hardhat@2.14.0/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js (https://esm.sh/v131/@uniswap/router-sdk@1.6.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/router-sdk.development.mjs:2972:61)
    at __require2 (https://esm.sh/v131/@uniswap/router-sdk@1.6.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/router-sdk.development.mjs:24:50)
    at ../esmd/npm/@uniswap/router-sdk@1.6.0/node_modules/.pnpm/@uniswap+router-sdk@1.6.0_hardhat@2.14.0/node_modules/@uniswap/router-sdk/dist/index.js (https://esm.sh/v131/@uniswap/router-sdk@1.6.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/router-sdk.development.mjs:3331:24)
    at __require2 (https://esm.sh/v131/@uniswap/router-sdk@1.6.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/router-sdk.development.mjs:24:50)
    at https://esm.sh/v131/@uniswap/router-sdk@1.6.0/X-ZS9AdW5pc3dhcC9zZGstY29yZSxAdW5pc3dhcC92My1zZGs/esnext/router-sdk.development.mjs:3364:24
```

## Additional info

- **esm.sh version**: 131
- **Deno version**: [in supabase](https://supabase.com/docs/guides/functions/local-development)

**Comment by ije** [comment]
did you fix it?

**Comment by soilSpoon** [comment]
> did you fix it?

Yes sorry I should have also put jsbi in external in @uniswap/router-sdk, my mistake
