### ISSUE TITLE
Tests mentioned in CONTRIBUTING.md are failing by default

### ISSUE THREAD

**Issue by mmuddasani** [esm-dev/esm.sh#734]
The contribution instructions [here](https://github.com/esm-dev/esm.sh/blob/main/CONTRIBUTING.md) mention to run tests via `./test/bootstrap.sh`. After immediately cloning the repository, the tests fail. This issue is blocking the development of contributions such as https://github.com/esm-dev/esm.sh/issues/686

Minor reason: the mentioned shell script `./test/bootstrap.sh` does not exist. OTOH, Deno script `./test/bootstrap.ts` does exist and is executable by default.

Major reason: Running `./test/bootstrap.ts` executes with a bunch of passing tests, followed by stopping at the first failure which occurs for `[test issue-502]`. Additionally, the failure can be reproduced by starting the development mode server, followed by visiting the link `http://localhost:8080/v132/es5-ext@0.10.62/denonext/string/$$/contains.js`

**Comment by mmuddasani** [comment]
The error can be reproduced by running `./test/bootstrap.ts --clean issue-502`. I've shared test output below when I executed from my local machine.

For some odd reason, there is a null byte "\x00" inside the offending URL.

Local output for test issue-502:
```
Cleaning up...
Starting esm.sh server...
Config file not found, use default config
2023/09/25 17:48:55 [info] nodejs v20.6.0 installed, registry: https://registry.npmjs.org/, pnpm: 8.7.6
2023/09/25 17:48:55 [info] Server is ready
esm.sh server started.

[test issue-502]
2023/09/25 17:48:57 [error] [ns] cjsLexer: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
---
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
    at Object.readFileSync (node:fs:465:12)
    at exports.parseCjsExports (/Users/mo/node_modules/.pnpm/esm-node-services@0.9.0/node_modules/esm-node-services/cjs-lexer.js:135:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IncomingMessage.<anonymous> (/Users/mo/.esmd/ns/ns.js:20:20)
---
2023/09/25 17:48:57 [error] build 'v132/es5-ext@0.10.62/denonext/string/#/contains.js': cjsLexer: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
2023/09/25 17:48:58 [error] [ns] cjsLexer: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
---
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
    at Object.readFileSync (node:fs:465:12)
    at exports.parseCjsExports (/Users/mo/node_modules/.pnpm/esm-node-services@0.9.0/node_modules/esm-node-services/cjs-lexer.js:135:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IncomingMessage.<anonymous> (/Users/mo/.esmd/ns/ns.js:20:20)
---
2023/09/25 17:48:58 [error] build 'v132/es5-ext@0.10.62/denonext/string/#/contains.js': cjsLexer: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/mo/.esmd/npm/es5-ext@0.10.62/node_modules/.pnpm/es5-ext@0.10.62/node_modules/es5-ext/string/\x00#/contains/index.js'
error: Import 'http://localhost:8080/v132/es5-ext@0.10.62/denonext/string/$$/contains.js' failed: 500 Internal Server Error
    at http://localhost:8080/d@1.0.1:6:8
Closing esm.sh server...
```

**Comment by ije** [comment]
may i ask what it is your os? seems it works for me(macOS m1) and the CI(linux, ubuntu)
