### ISSUE TITLE
Failed to import - @google-cloud/pubsub

### ISSUE THREAD

**Issue by yzalium** [esm-dev/esm.sh#768]
Hello,

This package works with npm import `npm:@google-cloud/pubsub`, but I'm getting an error when attempting to import with esm

## Failing module

- **npm**: https://www.npmjs.com/package/@google-cloud/pubsub

```typescript
import { PubSub } from "https://esm.sh/@google-cloud/pubsub";
```

## Error message

```
Uncaught TypeError: Cannot read properties of undefined (reading 'DEADLINE_EXCEEDED')
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:99164
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:458
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:101751
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:458
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:112692
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:458
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:120334
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:458
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:124744
    at https://esm.sh/v135/@google-cloud/pubsub@4.0.7/denonext/pubsub.mjs:47:458
```

## Additional info

- **esm.sh version**: `v135`
- **Deno version**: `v1.38.3 (release, aarch64-apple-darwin)`

Thank you

**Comment by Ariaszzzhc** [comment]
Any progress? I went same error when importing  @google-cloud/pubsub

**Comment by ije** [comment]
i will check

**Comment by ije** [comment]
does `npm:` specifier work?

```js
import { PubSub } from "npm:@google-cloud/pubsub"
```

**Comment by yzalium** [comment]
The import works yes. It fails later down the road when using the package because of some missing polyfills in Deno, and I wanted to try with esm in case you guys were covering those.
