### ISSUE TITLE
Failed to import - @vuepic/vue-datepicker

### ISSUE THREAD

**Issue by 9mm** [esm-dev/esm.sh#782]
## Failing module

- **GitHub**: https://github.com/Vuepic/vue-datepicker
- **npm**: https://www.npmjs.com/package/@vuepic/vue-datepicker

```js
import VueDatePicker from '@vuepic/vue-datepicker';
```

## Error message

After `onload` I got this:

```
vue.esm-browser.prod.min.js:1 TypeError: Cannot read properties of null (reading 'setupContext')
    at Br (runtime-core.esm-bundler.js:3324:12)
    at Ui (runtime-core.esm-bundler.js:3265:10)
    at setup (vue-datepicker.js:4655:29)
    at sn (vue.esm-browser.prod.min.js:1:17045)
    at z (vue.esm-browser.prod.min.js:1:54932)
    at w (vue.esm-browser.prod.min.js:1:51461)
    at q (vue.esm-browser.prod.min.js:1:52434)
    at U (vue.esm-browser.prod.min.js:1:51793)
    at w (vue.esm-browser.prod.min.js:1:51320)
    at q (vue.esm-browser.prod.min.js:1:52434)
```

## Additional info

- **esm.sh version**: latest? but i do see it adds v135 some places
- **Browser version**: Chrome 120

**Comment by ije** [comment]
i think you need to fix the vue version by adding the `?deps` flag

```js
import "https://esm.sh/@vuepic/vue-datepicker?deps=vue@3.5.8"
```

or use import maps:


```html
<script type="importmap">
{
  "@vuepic/vue-datepicker": "https://esm.sh/@vuepic/vue-datepicker?external=vue",
  "vue": "https://esm.sh/vue@3"
}
</sciprt>
```
