### ISSUE TITLE
Failed to import - @web3-storage/w3up-client

### ISSUE THREAD

**Issue by talentlessguy** [esm-dev/esm.sh#787]
## Failing module

- **GitHub**: https://github.com/web3-storage/w3up/tree/main/packages/w3up-client
- **npm**: https://www.npmjs.com/package/@web3-storage/w3up-client

```js
import { create } from 'https://esm.sh/@web3-storage/w3up-client'
```

## Error message

After running `deno run` I got this:

```
Uncaught TypeError: Import 'https://esm.sh/v135/@ucanto/core@9.0.1/denonext/src/lib.js' failed: 500 Internal Server Error
    at https://esm.sh/v135/@ucanto/core@9.0.1/denonext/core.mjs:2:1389
    at async <anonymous>:1:41
```

opening in the browser yields this:

```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No matching export in \"../esmd/npm/@ucanto/core@9.0.1/node_modules/.pnpm/@ucanto+core@9.0.1/node_modules/@ucanto/core/src/lib.js\" for import \"panic\"");
export default null;
```

## Additional info

- **esm.sh version**: v135
- **Deno version**: 1.39.1

**Comment by talentlessguy** [comment]
Same happens with:

```js
import { Agent } from 'https://esm.sh/@web3-storage/access@18.1.0/agent'
const agent = await Agent.create()
```

**Comment by talentlessguy** [comment]
new error on v135:

```
Uncaught TypeError: Import 'https://esm.sh/v135/@ucanto/core@10.0.1/denonext/src/lib.js' failed: 500 Internal Server Error
    at https://esm.sh/v135/@ucanto/core@10.0.1/denonext/core.mjs:2:1443
    at https://esm.sh/v135/@ucanto/core@10.0.1/denonext/core.mjs:2:1443
    at async <anonymous>:1:40
```

**Comment by ije** [comment]
still fail on dev branch

```
> import { create } from 'https://next.esm.sh/@web3-storage/w3up-client'
Uncaught TypeError: Module not found "https://next.esm.sh/@ucanto/core@10.0.1/denonext/src/src/invocation.mjs".
    at https://next.esm.sh/@ucanto/core@10.0.1/denonext/src/lib.mjs:2:203
    at https://next.esm.sh/@ucanto/core@10.0.1/denonext/src/lib.mjs:2:203
    at async <anonymous>:1:41
```
