### ISSUE TITLE
Failed to import - blockly

### ISSUE THREAD

**Issue by joeftiger** [esm-dev/esm.sh#878]
## Failing module

- **GitHub**: https://github.com/google/blockly
- **npm**: https://www.npmjs.com/package/blockly

```ts
import "https://esm.sh/blockly@11.1.1";
```

## Error message

After running `deno run` I got this:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createBlockDefinitionsFromJsonArray$$module$build$src$core$common')
    at https://esm.sh/v135/blockly@11.1.1/denonext/blocks.js:4:1024
    at https://esm.sh/v135/blockly@11.1.1/denonext/blocks.js:4:923
    at https://esm.sh/v135/blockly@11.1.1/denonext/blocks.js:4:983
    at https://esm.sh/v135/blockly@11.1.1/denonext/blocks.js:4:459
    at https://esm.sh/v135/blockly@11.1.1/denonext/blocks.js:6:48221
```

## Additional info

- **esm.sh version**: v135
- **Deno version**: 1.45 - 1.46.3

**Comment by ije** [comment]
thanks! i can confirm this also doesn't work on _dev_ branch, i will look into it!

<img width="1147" alt="Screenshot 2024-09-10 at 17 53 53" src="https://github.com/user-attachments/assets/694fefd1-6063-4cfb-ba4b-663cff5f5140">
