### ISSUE TITLE
chroma-js fails to generate colors from a predefined scale

### ISSUE THREAD

**Issue by eevleevs** [esm-dev/esm.sh#898]
Since 3.1.1, the following fails in both browser and Deno:

```
import chroma from 'https://esm.sh/chroma-js@3.1.1'
chroma.scale('Set3').colors(5)
```

> Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
>     at p (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/utils/unpack.js:2:207)
>     at Object.test (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/io/rgb.js:2:1254)
>     at new B (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/generator/scale.js:2:416)
>     at H (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/generator/scale.js:2:702)
>     at l (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/generator/scale.js:2:1886)
>     at https://esm.sh/v135/chroma-js@3.1.2/denonext/src/generator/scale.js:2:3291
>     at Array.map (<anonymous>)
>     at Function.l.colors (https://esm.sh/v135/chroma-js@3.1.2/denonext/src/generator/scale.js:2:3284)
>     at <anonymous>:1:43

**Comment by djtriptych** [comment]
I have the same issue. Copying and pasting similar code from the docs =(
