### ISSUE TITLE
Failed to import - octokit (types)

### ISSUE THREAD

**Issue by ThisGuyCodes** [esm-dev/esm.sh#918]
## Failing module

- **GitHub**: https://github.com/octokit/octokit.js
- **npm**: https://www.npmjs.com/package/octokit

```js
import { App } from "https://esm.sh/octokit"
```

## Error message
from a blank directory:
```shell
$ deno run -A -r https://esm.sh init
$ deno task esm:add octokit
```

make `test.ts` with the following contents:
```js
import { App } from "https://esm.sh/octokit"
```
After running `deno check test.ts` I got this:

```
error: Failed resolving types. Relative import path "@octokit/core/types" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts"
    at https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts:4:59
```

## Additional info

- **esm.sh version**: v135
- **Deno version**: v2.0.6

**Comment by ThisGuyCodes** [comment]
at first I thought this might be an octokit issue (I had [found something else](https://github.com/octokit/octokit.js/issues/2759) already). I [opened an issue there](https://github.com/octokit/octokit.js/issues/2762) first and they showed the mapping exists.

**Comment by wolfy1339** [comment]
This issue was already fixed in `@octokit/app`
https://github.com/octokit/app.js/pull/583

**Comment by wolfy1339** [comment]
I'm thinking you meant the other issue, where it can't resolve `@octokit/core/types`
```
$ deno check *.ts **/*.ts --allow-import
error: Failed resolving types. Relative import path "@octokit/core/types" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts"
    at https://esm.sh/v135/octokit@4.0.2/X-ZS8q/dist-types/octokit.d.ts:4:59
```

Which has to do with `exports` map, and a type only import

**Comment by ThisGuyCodes** [comment]
@wolfy1339 yes. I linked to both issues. I pasted the wrong logs here.

**Comment by ThisGuyCodes** [comment]
@wolfy1339 although idk why but `https://esm.sh/octokit` still seems to be resolving to the older version of `@octokit/app`

**Comment by ThisGuyCodes** [comment]
@wolfy1339 thanks for the workaround. Though it seems this just moved on to something else :(
```shell
$ deno check test.ts
error: Failed resolving types. Relative import path "node" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/@octokit/types@13.6.0/dist-types/RequestRequestOptions.d.ts"
    at https://esm.sh/v135/@octokit/types@13.6.0/dist-types/RequestRequestOptions.d.ts:1:22
```

it genuinely seems like I'm the only one doing this...

**Comment by ije** [comment]
i will look into it

**Comment by ije** [comment]
seems it's the type checking changed in deno 2, deno 1.x works fine
<img width="400" alt="Screenshot 2024-11-20 at 16 34 15" src="https://github.com/user-attachments/assets/4038496a-9bfd-4818-9cb4-651ffe8c3849">
<img width="600" alt="Screenshot 2024-11-20 at 16 34 49" src="https://github.com/user-attachments/assets/df132560-d279-4a02-908a-260bb2a57c87">

**Comment by ije** [comment]
https://github.com/denoland/deno/issues/25762

**Comment by wolfy1339** [comment]
That particular issue was resolved, it was a bug in the package. Can you please update `@octokit/app` on esm.sh

You need to force it to use `@octokit/app@15.1.1` in order to actually experience the issue described here

**Comment by ije** [comment]
@wolfy1339  thanks

**Comment by wolfy1339** [comment]
I'm not sure we understood each other.
The previous comment I made was about the file `web.d.ts` not existing and not about the issue as a whole.

The issue is still going on, and it isn't about module augmentation in types but `package.json` exports.

ESM.sh isn't resolving the import of `@octokit/core/types` to `@octokit/core/dist-types/types.d.ts` as defined in the `exports` map in the `package.json`

https://unpkg.com/browse/@octokit/core@6.1.3/package.json#L64
