### ISSUE TITLE
Failed to import - Relative import path "events" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by AnInternetTroll** [esm-dev/esm.sh#958]
## Failing module

- **GitHub**: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/62176d919ccdadfead789c8820941ea97005dbd2/types/node/events.d.ts#L929
- **npm**: https://npmjs.com/package/@types/node

(version 20.11.20)

```sh
deno check https://esm.sh/v135/@types/node@20.11.20/events.d.ts
```

## Error message

This only fails type checking of this module, and dependent modules (such as jsdom). At runtime it works as expected.

After running `deno check` I got this:

```
error: Relative import path "events" not prefixed with / or ./ or ../
  hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:events").
    at https://esm.sh/v135/@types/node@20.11.20/events.d.ts:878:29
```

## Additional info

- **Deno version**:

deno 2.1.4 (stable, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2

**Comment by ije** [comment]
@AnInternetTroll thanks, i will fix it in next deploy

**Comment by ije** [comment]
this is related to [denoland/deno#https://github.com/denoland/deno/issues/23007](https://github.com/denoland/deno/issues/23007)

**Comment by AnInternetTroll** [comment]
According to the linked deno bug this should be fixed now, but it isn't 
No idea why, which is unfortunate :/
```sh
$ deno --version
deno 2.2.4 (stable, release, x86_64-unknown-linux-gnu)
v8 13.4.114.11-rusty
typescript 5.7.3
$ deno check --reload https://esm.sh/@types/node
error: Failed resolving types. Relative import path "worker_threads" not prefixed with / or ./ or ../
  hint: If you want to use a built-in Node module, add a "node:" prefix (ex. "node:worker_threads").
    at https://esm.sh/@types/node@22.13.10/globals.d.ts:265:53
```
